package com.ofb.api;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

class OrderItems {
	public String orderId;
	public String orderItemSeqId;
	public String externalId;
	public String orderItemTypeId;
	public String orderItemGroupSeqId;
	public String isItemGroupPrimary;
	public String fromInventoryItemId;
	public String budgetId;
	public String budgetItemSeqId;
	public String productId;
	public String upc;
	public String upc_modifier;
	public String supplierProductId;
	public String productFeatureId;
	public String prodCatalogId;
	public String productCategoryId;
	public String isPromo;
	public String quoteId;
	public String quoteItemSeqId;
	public String shoppingListId;
	public String shoppingListItemSeqId;
	public String subscriptionId;
	public String deploymentId;
	public BigDecimal quantity;
	public BigDecimal cancelQuantity;
	public BigDecimal selectedAmount;
	public BigDecimal unitPrice;
	public BigDecimal unitListPrice;
	public BigDecimal unitAverageCost;
	public BigDecimal unitRecurringPrice;
	public String isModifiedPrice;
	public String recurringFreqUomId;
	public String itemDescription;
	public String comments; 
	public String correspondingPoId;
	public String statusId;
	public String syncStatusId;
	public Date estimatedShipDate;
	public Date estimatedDeliveryDate;
	public Date autoCancelDate;
	public Date dontCancelSetDate;
	public String dontCancelSetUserLogin;
	public Date shipBeforeDate;
	public Date shipAfterDate;
	public Date cancelBackOrderDate;
	public String overrideGlAccountId;
	public String salesOpportunityId;
	public String changeByUserLoginId;
	public Date lastUpdatedStamp;
	public Date lastUpdatedTxStamp;
	public Date createdStamp;
	public Date createdTxStamp;
	public String departmentId;
	public String departmentName;
	public String parentProductId;
}

class OrderPayments {
	public String paymentId;
	public String paymentTypeId;
	public String paymentMethodTypeId;
	public String paymentMethodId;
	public String paymentGatewayResponseId;
	public String paymentPreferenceId;
	public String partyIdFrom;
	public String partyIdTo;
	public String roleTypeIdTo;
	public String statusId;
	public Date effectiveDate;
	public String paymentRefNum;	
	public BigDecimal amount; 
	public String currencyUomId;
	public String comments;
	public String finAccountTransId;
	public String overrideGlAccountId;
	public BigDecimal actualCurrencyAmount;
	public String actualCurrencyUomId;
	public String paymentSubType;
	public String authCode;
	public Date lastUpdatedStamp;
	public Date lastUpdatedTxStamp;
	public Date createdStamp;
	public Date createdTxStamp;
}

class OrderAdjustments {
	public String orderAdjustmentId; 
	public String orderAdjustmentTypeId;            
	public String orderId;
	public String orderItemSeqId;
	public String shipGroupSeqId;
	public String comments;
	public String description;
	public BigDecimal amount;
	public BigDecimal recurringAmount;
	public BigDecimal amountAlreadyIncluded;
	public String productPromoId;
	public String productPromoRuleId;
	public String productPromoActionSeqId;
	public String productFeatureId;
	public String correspondingProductId;
	public String taxAuthorityRateSeqId;
	public String sourceReferenceId;
	public BigDecimal sourcePercentage;
	public String customerReferenceId;
	public String primaryGeoId;
	public String secondaryGeoId;
	public BigDecimal exemptAmount;
	public String taxAuthGeoId;
	public String taxAuthPartyId;
	public String overrideGlAccountId;
	public String includeInTax;
	public String includeInShipping;
	public String isManual;
	public Date createdDate;
	public String createdByUserLogin;
	public String lastModifiedDate;
	public String lastModifiedByUserLogin;
	public String originalAdjustmentId;
	public BigDecimal oldAmountPerQuantity;
	public BigDecimal oldPercentage;
	public Date lastUpdatedStamp;
	public Date lastUpdatedTxStamp;
	public Date createdStamp;
	public Date createdTxStamp;
}

class OrderAttributes {
	public String orderId; 
	public String attrName; 
	public String attrValue;        
	public String attrDescription;    
	public Date lastUpdatedStamp;
	public Date lastUpdatedTxStamp;
	public Date createdStamp;
	public Date createdTxStamp;
}

public class OrderWithDetails {
    public int resultCode;
    public String resultText;
    public String token;
	public String orderId;
	public String orderTypeId;
	public String salesChannelEnumId;
	public Date orderDate;
	public String statusId;
	public String createdBy;
	public String crPartyId;
	public String currencyUom;
	public String productStoreId;
	public String terminalId;
	public String billingAccountId;
	public String transactionId;
	public BigDecimal remainingSubTotal;
	public BigDecimal grandTotal;
	public String upc;
	public String externalId;
	public String orderName;
	public String internalCode;
	public String sourceOrderId;
	public BigDecimal taxAmount;	
	public String note;
	public String responseNote;
	public String customerName;
	public String loyaltyCard;
	public Date datePickup;
	public String applicationId;
	public Date lastUpdatedStamp;
	public Date lastUpdatedTxStamp;
	public Date createdStamp;
	public Date createdTxStamp;
	public List <OrderItems> orderItems;
	public List <OrderPayments> orderPayments;
	public List <OrderAdjustments> orderAdjustments;
	public List <OrderAttributes> orderAttributes;
}
